itapps/urls.py
from django.contrib import admin
from django.urls import path, include
from itreporting import views
from users import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from itreporting.views import PostListView, PostDetailView, PostCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itreporting/', include('itreporting.urls')),  
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name = 'profile'),
    path('report', views.profile, name = 'Report' ),
    path('issue/new', PostCreateView.as_view(), name = 'issue-create'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itreporting/urls.py
from django.urls import path, include
from . import views
from .views import PostListView, PostDetailView
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
app_name = 'itreporting'

urlpatterns = [ 
    path('', views.home, name = 'home'),
    path('about', views.about, name = 'about'),
    path('contact', views.contact, name = 'contact'),
    path('report/', PostListView.as_view(), name = 'report'),
    path('issues/<int:pk>', PostDetailView.as_view(), name = 'issue-detail'),
    path('issue/<int:pk>/update/', PostUpdateView.as_view(), name = 'issue-update'),
    path('issue/<int:pk>/delete/', PostDeleteView.as_view(), name = 'issue-delete'),
    path('issues/create/', PostCreateView.as_view(), name='issue-create'),

 ]

itreporting/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Issue(models.Model):
    type = models.CharField(max_length=100, choices=[('Hardware', 'Hardware'), ('Software', 'Software')])
    room = models.CharField(max_length=100)
    urgent = models.BooleanField(default=False)
    details = models.TextField()
    date_submitted = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    author = models.ForeignKey(User, related_name='issues', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.type} Issue in {self.room}'
    
    def get_absolute_url(self):
        return reverse('itreporting:issue-detail', kwargs={'pk': self.pk})
        
    

users/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    image = models.ImageField(default='media/profile_pics/default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    
    email = forms.EmailField(label='Email address', help_text='')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

itreporting/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from itreporting.models import Issue


def home(request): 
    return render(request, 'itreporting/home.html', {'title': 'Welcome'})


def about(request): 
    return render(request, 'itreporting/about.html', {'title': 'Welcome'})


def contact(request):
    return render(request, 'itreporting/contact.html', {'title': 'Welcome'})


def report(request):
    daily_report = {'issues': Issue.objects.all(), 'title': 'Issues Reported'}
    return render(request, 'itreporting/report.html', daily_report)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Issue
    fields = ['type', 'room', 'urgent', 'details']
    template_name = 'itreporting/issue_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostListView(ListView):
    model = Issue
    ordering = ['-date_submitted']
    template_name = 'itreporting/report.html'
    context_object_name = 'issues'
    paginate_by = 10


class PostDetailView(DetailView):
    model = Issue
    template_name = 'itreporting/issue_detail.html'


class PostUpdateView(LoginRequiredMixin, UpdateView): 
    model = Issue
    fields = ['type', 'room', 'details']


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Issue
    success_url = '/report'
    
    def test_func(self):
        issue = self.get_object()
        return self.request.user == issue.author

users/views.py
from django.shortcuts import render
from .forms import UserRegisterForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required  
from django.shortcuts import render

def profile(request):

    return render(request, 'users/profile.html', {'title': 'Student Profile'})

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! Now you can login!') 
            return redirect('login')

        else:
            messages.warning(request, 'Unable to create account.')
    else:
        form =UserRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'title': 'Student Registration'})


@login_required
def profile(request):
    return render(request, 'users/profile.html', {'title': 'Student Profile'})

itreporting/templates/itreporting/about.html
{% extends "itreporting/base.html" %}


{% block content %}
<h1>Welcome to SHU about</h1>
{% endblock %}

itreporting/templates/itreporting/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />

    <title>Student IT Services - {{title}}</title>
</head>
<body>
    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'itreporting:home' %}">Student IT Services</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'itreporting:home' %}">Home</a>
                        <!-- <a class="nav-item nav-link" href="{% url 'itreporting:about' %}">About</a>
                        <a class="nav-item nav-link" href="#">Report</a> -->
                       <!--<a class="nav-item nav-link" href="{% url 'itreporting:contact' %}">Contact</a> -->
                       <a class="nav-item nav-link" href="{% url 'itreporting:report' %}">Reportr</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                         <form method="post" id="frm_logout" action="{% url 'logout' %}" style="display:inline;">
                          {% csrf_token %}
                           <button type="submit" class="nav-item nav-link" style="background:none; border:none; cursor:pointer;">Logout</button>
                                                    </form>
                         {% else %}
                          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                         <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                          {% endif %}
                          </div>
                        

                    </div>
                </div>
                </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>General Information</h3>
                    <p class='text-muted'>Lorem ipsum dolor sit amet, iudico docendi inciderint per eu, ea vis scripta senserit periculis.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Issues Reported</li>
                        <li class="list-group-item list-group-item-light">IT Policies</li>
                        <li class="list-group-item list-group-item-light">IT Regulations</li>
                        <li class="list-group-item list-group-item-light">Upcoming Events</li>
                      </ul>
                    </p>
                  </div>
            </div>
        </div>
    </div>

    <div class="navbar-nav"> 

        {% if user.is_authenticated  %} 
            <a class="nav-item nav-link" href="{% url 'itreporting:issue-create' %}">Report New Issue</a>
    
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a> 
    
        {% else %} 
    
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a> 
    
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a> 
    
        {% endif %} 
    
     </div>
    
     </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script></body>

</html>

itreporting/templates/itreporting/contact.html
{% extends "itreporting/base.html" %}


{% block content %}
<h1>Welcome to SHU contact</h1>
{% endblock %}

itreporting/templates/itreporting/home.html
{% extends "itreporting/base.html" %}


{% block content %}
<h1>Welcome to SHU!</h1>
{% endblock %}

itreporting/templates/itreporting/issue_confirm_delete.html
{% extends "itreporting/base.html" %} 

{% block content %} 

<div class="content-section"> 

    <form method="POST"> 

        {% csrf_token %} 

        <fieldset class="form-group"> 

            <legend class="border-bottom mb-4">Delete IT issue</legend> 

          
        </fieldset> 

        <div class="form-group"> 

            <button class="btn btn-outline-danger" type="submit">Delete</button> 
            <a class="btn btn-outline-secondary" href="{% url 'itreporting:issue-detail' object.id %}">Cancel</a>

        </div> 

    </form> 

    </div> 

{% endblock content %} 

itreporting/templates/itreporting/issue_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>IT Issues Reported</title>
</head>
<body>
    <h1>IT Issues Reported</h1>

        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ object.author.profile }}</a>
                    <small class="text-muted">{{ object.date_submitted }}</small>
                </div>
                <h2 class="article-title">{{ object.type    }} Issue in Room {{object.room}}</h2>
                <p class="article-content">{{ object.details }}</p>
                        {% if object.author == user %}

                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'itreporting:issue-update' object.id %}">Update</a>

                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'itreporting:issue-delete' object.id %}">Delete</a>

                        {% endif %}

            </div>
        </article>

</body>
</html>

itreporting/templates/itreporting/issue_form.html
{% extends "itreporting/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-section"> 
 
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">

            <legend class="borer-bottom mb-4"> Report IT Issue </legend>
            {{ form|crispy }}

        </fieldset>
        <div class="form-group">

            <button class="btn btn-outline-info"  type="submit">Submit</button>
        </div> 

    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Are you already Registered? <a class="ml-2" href="#">Login </a></small>
        
    </div> 
</div>

{% endblock content %}

itreporting/templates/itreporting/report.html
<!DOCTYPE html>
<html>
<head>
    <title>Issues Reported</title>
</head>
<body>

<h1>Issues Reported</h1>
{% for issue in issues %}
    <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ issue.author.profile.image.url }}"/>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ issue.author.profile }}</a>
                <small class="text-muted">{{ issue.date_submitted }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'itreporting:issue-detail' issue.id %}">{{ issue }}</a></h2>
            <p class="article-content">{{ issue.details }}</p>
        </div>
    </article>

{% endfor %}

</body>
</html>

users/templates/users/login.html
{% extends "itreporting/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %} 
<div class="content-section"> 
    <form method="POST"> 
        {% csrf_token %} 
        <fieldset class="form-group"> 
            <legend class="border-bottom mb-4">Student IT Services - Login</legend> 
            {{ form|crispy}} 
        </fieldset> 
        <div class="form-group"> 
            <button class="btn btn-outline-info" type="submit">Login</button> 
        </div> 
    </form> 
    <div class="border-top pt-3"> 
        <small class="text-muted"> 
        You need to create an account?<a class="ml-2" href="{% url 'login' %}">Login</a> 
        </small> 
    </div> 
</div> 
{% endblock content %}

users/templates/users/logout.html
{% extends "itreporting/base.html" %} 
{% block content %} 
    <h2>You have now been logged out</h2> 
        <div class="border-top pt-3"> 
            <small class="text-muted"><a class="ml-2" href="{% url 'login' %}">Login</a></small> 
        </div> 
{% endblock content %}

users/templates/users/profile.html
{% extends "itreporting/base.html" %}

{% block content %}

<div class="content-section"> 

  <div class="media"> 

   <p><img class="rounded-circle account-img" src="{{user.profile.image.url}}"></p> 

    <div class="media-body"> 

      <h2 class="account-heading">{{user.profile}}</h2> 

      <p class="text-secondary">{{user.username}}</p> 

      <p class="text-secondary">{{user.email}}</p> 

    </div> 

  </div> 

</div> 

{% endblock content %}

users/templates/users/register.html
{% extends "itreporting/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Student Registration Form</legend>
            {{ form | crispy }}
                </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Registered? <a class="ml-2" href="#">Login</a>
        </small>
    </div>
</div>
{% endblock content %}